POST https://expressjs-2jr8.onrender.com/api/greet
content-type: application/json

{
	"language" : "xhosa",
	"greeting" : "Molo"
}

### 

POST https://expressjs-2jr8.onrender.com/api/greet
content-type: application/json

{
	"language" : "zulu",
	"greeting" : "Sawubona"
}